#!/bin/bash
#PBS -N GRCm38_bcftools_vcf                                                                                      # Job name
#PBS -l nodes=1:ppn=16                                                                                          # Nodes & cores
#PBS -l walltime=10:00:00                                                                                       # Maximal time
#PBS -o /data/gent/471/vsc47196/Thesis_Opdrachten/Mouse_Haploidisation/GRCm38_SNP/Output                        # Output directory
#PBS -e /data/gent/471/vsc47196/Thesis_Opdrachten/Mouse_Haploidisation/GRCm38_SNP/Errors                        # Error directory


module load BCFtools/1.18-GCC-12.3.0
module load SAMtools/1.18-GCC-12.3.0


#GRCm38_SNP_call
bcftools mpileup -Ou -f /scratch/gent/vo/001/gvo00115/vsc47196/Reference_Genomes/GRCm38/GRCm38.fa \
  /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/SNP/180123WV2CP_DNA093258_S40_GRCm38.bam | \
bcftools call -mv -Ov --ploidy 1 \
  -o /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/SNP/bcftools/180123WV2CP_DNA093258_S40_GRCm38_bcftools.vcf
  

#DBA2_SNP_call  
bcftools mpileup -Ou -f /scratch/gent/vo/001/gvo00115/vsc47196/Reference_Genomes/DBA2/DBA_2J_Ensembl.fa \
  /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/SNP/180123WV2CP_DNA093258_S40_DBA2.bam | \
bcftools call -mv -Ov --ploidy 1 \
  -o /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/SNP/bcftools/180123WV2CP_DNA093258_S40_DBA2_bcftools.vcf
