#!/bin/bash
#PBS -N M_Hapl_Align_Controls                                                                                    #name
#PBS -l nodes=1:ppn=16                                                                                           #nodes & cores
#PBS -l walltime=10:00:00                                                                                        #max walltime
#PBS -t 1-52                                                                                                     #for the 52 controls
#PBS -o /data/gent/471/vsc47196/Mouse_Haploidisation/GRCm38_CNV/GRCm38_Controls/Output                           #output directory
#PBS -e /data/gent/471/vsc47196/Mouse_Haploidisation/GRCm38_CNV/GRCm38_Controls/Errors                           #error directory


#Loading necessary modules
module load Bowtie2/2.5.4-GCC-13.2.0
module load SAMtools/1.19.2-GCC-13.2.0
module load FastQC/0.12.1-Java-11
module load fastp/0.23.4-GCC-13.2.0

#Defining all controls to be ran in parallel
Controls=(
    180123WV4CEA_DNA093251_S33
    180123WV4CEB_DNA093253_S35
    180123WV11CE_DNA093255_S37
    180123WV9CE_DNA093257_S39
    180123WV2CP_DNA093258_S40
    180123WV10CE_DNA093249_S24
    180123WV4CPA_DNA093250_S32
    180123WV9CP_DNA093256_S38
    180123WV5CE_DNA093261_S43
    180123WV2BP_DNA093280_S51
    180123WV4CPB_DNA093252_S34
    180123WV11CP_DNA093254_S36
    180123WV2CE_DNA093259_S41      
    280123WVMmB2BEC1_DNA098404_S39
    280123WVMmB2BHC3_DNA098405_S40
    280123WVMmB2BHC6_DNA098406_S41
    280123WVMmB2BHC11_DNA098408_S42
    280123WVMmB2BHC13_DNA098409_S43
    280123WVMmB2BHC14_DNA098410_S44 
    290523WVMmB2BhCB_DNA100643_S36
    290523WVMmB2BECC_DNA100644_S37
    290523WVMmB2BECD_DNA100645_S38
    290523WVMmB2BHCE_DNA100646_S39
    290523WVMmB2BHCF_DNA100647_S40
    290523WVMmB2BHCG_DNA100648_S41
    290523WVMmB2BECK_DNA100652_S42
    290523WVMmB2BECN_DNA100665_S44
    290523WVMmB2BECO_DNA100666_S45
    290523WVMmB2BECP_DNA100667_S46
    290523WVMmB2BECQ_DNA100668_S47
    290523WVMmB2BECR_DNA100669_S48
    290523WVMmB2BECS_DNA100670_S49
    290523WVMmB2BECT_DNA100672_S50
    161123WVMmB2BHC1_DNA111944_S41
    161123WVMmB2BHC2_DNA111945_S42
    161123WVMmB2BHC3_DNA111946_S43
    161123WVMmB2BHC7_DNA111947_S44
    161123WVMmB2BHC8_DNA111948_S45
    270224WVMmBC1iMCP32_DNA117483_S50 
    270624WVMmB6eCP3_DNA127191_S36
    150724WVMmB6eCP4_DNA127217_S60
    160724WVMmB6eCP4_DNA127218_S61
    021024WVMmB6eCL14P4
    021024WVMmB6eCL17P4
    021024WVMmB6eCL18P4
    021024WVMmB6eCL19P4
    021024WVMmB6eCL5P4
    021024WVMmB6eCL7P4
    180123WV10CP_DNA093248_S23
    180123WV5CP_DNA093260_S42
    280123WVMmB2BHC9_DNA098407_S42
    290523WVMmB2BECM_DNA100664_S43
)


#Getting the current control ID
echo "PBS_ARRAYID: $PBS_ARRAYID"
Control=${Controls[$PBS_ARRAYID-1]}

#Paths
R1_cram="/scratch/gent/vo/001/gvo00115/vsc47196/Raw${Control}_L001.cram"
R2_cram="/scratch/gent/vo/001/gvo00115/vsc47196/Raw${Control}_L002.cram"

#Merging
#echo "Merging CRAM files for ${Control}"
samtools merge -f /scratch/gent/vo/001/gvo00115/vsc47196/Raw/Merged/Controls/${Control}.cram "$R1_cram" "$R2_cram"

#Converting the cram files to the fastq format
Merged_cram="/scratch/gent/vo/001/gvo00115/vsc47196/Raw/Merged/Controls/${Control}.cram"

echo "Checking CRAM file: $Merged_cram"

if [ -f "$Merged_cram" ]; then
    echo "CRAM merge successful for ${Control}, extracting FASTQ"
    samtools fastq -1 /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq/${Control}_R1.fastq.gz -2 /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq/${Control}_R2.fastq.gz "$Merged_cram"
    
    if [ $? -eq 0 ]; then
        echo "FASTQ extraction successful for ${Control}"
    else
        echo "Error: FASTQ extraction failed for ${Control}" >&2
        exit 1
    fi
else
    echo "Error: CRAM merging failed for ${Control}" >&2
    exit 1
fi

#Trimming
R1_Merged_fastq="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq/${Control}_R1.fastq.gz"
R2_Merged_fastq="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq/${Control}_R2.fastq.gz"

fastp -i "$R1_Merged_fastq" -I "$R2_Merged_fastq" \
      -o /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq_Trimmed/${Control}_R1_trimmed.fastq.gz -O /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq_Trimmed/${Control}_R2_trimmed.fastq.gz \
      --html /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq_Trimmed/Fastp_reports/${Control}.html \
      --dedup \
      --trim_front1 14 --trim_tail1 2 --trim_tail2 2 \
      --cut_front --cut_tail --cut_window_size 4 --cut_mean_quality 30 \
      --thread 4


#QC
R1_Trimmed_fastq="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq_Trimmed/${Control}_R1_trimmed.fastq.gz"
R2_Trimmed_fastq="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Fastq_Trimmed/${Control}_R2_trimmed.fastq.gz"

echo "Running FastQC for ${Control}"
fastqc "$R1_Trimmed_fastq" -o /data/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/QC_Trimmed/
fastqc "$R2_Trimmed_fastq" -o /data/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/QC_Trimmed/
echo "Finished FastQC for ${Control}"


#Allignment to bowtie2 and conversion from sam to bam, -p16 so that bowtie2 uses all nodes
echo "Running Bowtie2 alignment for ${Control}..."
bowtie2 -x /scratch/gent/vo/001/gvo00115/vsc47196/Reference_Genomes/GRCm38/GRCm38_index \
    -1 "$R1_Trimmed_fastq" \
    -2 "$R2_Trimmed_fastq" \
    --very-sensitive \
    -p 16 \
    --met-file /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments/Alignment_metrics/${Control}.txt | \
    samtools view -bS - | \
    samtools sort -o /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments/${Control}.bam

# Check if alignment was successful
if [ $? -eq 0 ]; then
    echo "Alignment successful for ${Control}"
else
    echo "Error: Alignment failed for ${Control}" >&2
    exit 1
fi
    
#Adjusting the header
Aligned_bam="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments/${Control}.bam"

echo "Reheadering BAM file for ${Control}"
samtools view -H "$Aligned_bam" > /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/${Control}_header.sam

Header="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/${Control}_header.sam"

sed -i 's/SN:chr/SN:/g' "$Header"

samtools reheader "$Header" "$Aligned_bam" > /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/${Control}_ChrName.bam


#Indexing
Adjusted_bam="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/${Control}_ChrName.bam"
Index_output_dir="/scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName"

echo "Indexing BAM file for ${Control}"
samtools index -b "$Adjusted_bam" "${Index_output_dir}/${Control}_ChrName.bam.bai"

# Checking if the index was created successfully
if [ -f "${Index_output_dir}/${Control}_ChrName.bam.bai" ]; then
    echo "Indexing successful for ${Control}"
else
    echo "Error: Indexing failed for ${Control}" >&2
    exit 1
fi

#Counting reads per chromosome
echo "Counting reads per chromosome for ${Control}"
samtools idxstats "$Adjusted_bam" > /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/Chromosome_Reads/${Control}_idxstats.txt

if [ $? -eq 0 ]; then
    echo "Chromosome read count successful for ${Control}"
else
    echo "Error: Read count failed for ${Control}" >&2
    exit 1
fi

#Quality control
echo "Running samtools flagstat for ${Control}"
samtools flagstat "$Adjusted_bam" > /scratch/gent/vo/001/gvo00115/vsc47196/Mouse_Haploidisation/CNV/GRCm38_Controls/Alignments_ChrName/Bam_QC/${Control}.txt

if [ $? -eq 0 ]; then
    echo "BAM quality check successful for ${Control}"
else
    echo "Error: BAM quality check failed for ${Control}" >&2
    exit 1
fi


#Cleaning up the temporary
if [ -d "$tmp_dir" ]; then
    rm -rf $tmp_dir
fi

echo "Finished alignment for ${Control}"
